[[main]]
name = "Início"
url = "/"
weight = 1

[[main]]
name = "Keynotes"
url = "#keynotes"
weight = 2

[[main]]
name = "Charlas"
url = "#schedule"
weight = 3

[[main]]
name = "Blog"
url = "#blog"
weight = 4

[[main]]
name = "Patrocinadores"
url = "#sponsors"
weight = 5

[[main]]
name = "Código de Conducta"
url = "/codigo-de-conducta/"
weight = 6
